steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/greenco-db/dbt-test/dbt-test', '.']

images:
  - 'us-central1-docker.pkg.dev/greenco-db/dbt-test/dbt-test'

options:
  logging: CLOUD_LOGGING_ONLY