# This is a basic workflow to help you get started with Actions

name: dbt CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt BigQuery
        run: pip install dbt-bigquery

      - name: Install dbt dependencies
        run: dbt deps

      - name: Create credentials file
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT }}' > keyfile.json

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          jaffle_shop_1:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: greenco-db
                dataset: TEST
                threads: 4
                keyfile: keyfile.json
          EOF

      - name: Test connection
        run: dbt debug

      - name: Run models
        run: dbt run

     # - name: Run tests
     #   run: dbt test
